replicaCount: 1

image:
  repository: spigrig/hello-spyros
  pullPolicy: IfNotPresent
  tag: latest

env:
  name: Spyros

service:
  type: NodePort
  port: 5000

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: []
