
# Configuration file for the Helm chart deployment of the web application.

# replicaCount: Number of replicas for the application deployment.
# image:
#   repository: Docker image repository for the application.
#   pullPolicy: Image pull policy (e.g., Always, IfNotPresent).
#   tag: Tag of the Docker image to be used.
# env:
#   name: Environment variable to set the application name.
# service:
#   name: Name of the service.
#   type: Type of the service (e.g., ClusterIP, NodePort, LoadBalancer).
#   port: Port on which the service will be exposed.
# serviceAccount:
#   create: Boolean to specify whether to create a new service account.
#   name: Name of the service account to use (leave empty for default).
# ingress:
#   enabled: Boolean to enable or disable ingress configuration.
# resources: Resource requests and limits for the application (CPU, memory).
# autoscaling:
#   enabled: Boolean to enable or disable horizontal pod autoscaling.
# nodeSelector: Node selector for scheduling the pods on specific nodes.
# tolerations: Tolerations for scheduling pods on tainted nodes.
# affinity: Affinity rules for scheduling pods on specific nodes.
replicaCount: 1

image:
  repository: spigrig/hello-spyros
  pullPolicy: IfNotPresent
  tag: latest

env:
  name: Spyros

service:
  name: webapp
  type: NodePort
  port: 5000

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: []