# Configuration for the deployment of the application
# 
# replicaCount: Number of replicas for the application.
# 
# image:
#   repository: The Docker image repository for the application.
#   pullPolicy: The image pull policy (e.g., Always, IfNotPresent).
#   tag: The tag of the Docker image to use.
# 
# env:
#   name: The environment variable specifying the name to be used in the application.
# 
# service:
#   type: The type of Kubernetes service (e.g., ClusterIP, NodePort, LoadBalancer).
#   port: The port on which the service is exposed.
# 
# serviceAccount:
#   create: Specifies whether a service account should be created.
#   name: The name of the service account to use. Leave empty to use the default.
# 
# ingress:
#   enabled: Specifies whether ingress is enabled for the application.
# 
# resources: Resource requests and limits for the application. Leave empty for default.
# 
# autoscaling:
#   enabled: Specifies whether autoscaling is enabled for the application.
# 
# nodeSelector: Node selector for scheduling the application pods.
# 
# tolerations: Tolerations for scheduling the application pods on tainted nodes.
# 
# affinity: Affinity rules for scheduling the application pods.
replicaCount: 1

image:
  repository: spigrig/hello-spyros
  pullPolicy: IfNotPresent
  tag: latest

env:
  name: Spyros

service:
  type: NodePort
  port: 5000

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: []